### ISSUE TITLE
IE11: nav logo is not rendering

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonworks_homepage#15]
It seems the logo is not displayed on the nav using IE11
![logo missing](https://user-images.githubusercontent.com/16530364/27158464-7e2bc500-513d-11e7-90cf-3d203b52aa2f.png)

**Comment by mjy** [comment]
Also missing on FF dev.  Blocks #8.

**Comment by mjy** [comment]
Duplicate of #8
