### ISSUE TITLE
IE11 JS exceptions 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_homepage#2]
* The navigation bar never appears
* The scope is also blown out with no navigation available

Recommendation:
* Implement a non-JS solution for the mobile nav. This is not a critical error though. User can still scroll the page fine without it.
* Fix IE11 errors in the JS for the scope section. Make sure there is a graceful fallback in case JS fails.

**Comment by BrianWalters** [comment]
Hey Matt and Jose,

Found out this was IE11 choking from `Array.from` calls, which isn't supported in any IE. Fortunately, it's a function that easy to polyfill. I added the `babel-polyfill` package to the build and now the scope section is smooth as butter in my IE11 VM. That package also covers some other ES2015 helpers like `Object.assign`.

Merged into develop

**Comment by LocoDelAssembly** [comment]
@jlpereira @mjy even if IE is still broken I guess we don't care anymore?

**Comment by jlpereira** [comment]
Its not broken, Brian already fixed this. Closing
