### ISSUE TITLE
As a devop I'd like to do a build/release

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_homepage#25]

**Comment by LocoDelAssembly** [comment]
Should this be setup like taxonworks_api or manual build is preferred?

**Comment by mjy** [comment]
This issue is a manual build.  #24 is a request for something like tw_api

**Comment by LocoDelAssembly** [comment]
Closed by https://github.com/SpeciesFileGroup/taxonworks_homepage/commit/f6ec705745c514b71f6496a8f2190bd4d236288e
