### ISSUE TITLE
taxonworks.org footer need to replace old INHS logo with new one

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks_homepage#27]
Issue: old INHS logo in footer at taxonworks.org

Request from Trish Barker (Associate Director for Strategic Communications; Prairie Research Institute)
- please replace old INHS patchwork quilt logo [seen in footer here ](https://taxonworks.org/) with this one
- https://inhs.illinois.edu/
![University-Wordmark-Reversed-Orange-RGB](https://user-images.githubusercontent.com/2990155/177413176-61fe3d19-dc93-4af5-a5c2-71c220eec403.svg)

- note letters are "white" in the above SVG and this won't work on the taxonworks.org footer because it's also white.
- perhaps there's another version (but I couldn't find one). I sent Trish a note to ask.

CLARIFICATION from Trish:
"Well, there is no INHS logo any longer. There's just the U of I wordmark and the U of I logo (the Block I). You can use the name "Illinois Natural History Survey" but it should be separated from the wordmark or logo by sufficient space -- this webpage describes the amount of clearance that is required: https://marketing.illinois.edu/design/logo. 

This Box folder has multiple options for the wordmark and Block I logo: https://uofi.box.com/s/irsuwtayeo29p666iqd7ejfzikwl802w. "

**Comment by LocoDelAssembly** [comment]
I don't have access to that box folder and I guess the situation will be worse for José. Not sure if it a good idea to post it here anyway?

Is only the footer that needs change? The logo is also used somewhere up.

**Comment by jlpereira** [comment]
I will do it when I get back

**Comment by debpaul** [comment]
> Is only the footer that needs change? The logo is also used somewhere up.

@jlpereira Trish notes that there is no more "INHS quilt logo" so I would guess wherever we have it, it needs to be replaced... to look like this:

![image](https://user-images.githubusercontent.com/2990155/178843348-91303454-072b-464e-ac63-4eca90b303e2.png)
and maybe a discussion about whether we need the address?
![image](https://user-images.githubusercontent.com/2990155/178843421-3acb79f5-9042-4463-8264-9112cfabf4ea.png)

I note too, that I can provide access to box when needed. But we can always get Trish to resend a Box link to you or @LocoDelAssembly if needed. Main issue I see is **white letters.**

**Comment by jlpereira** [comment]
@debpaul can you download the logos and send them to me? I don't have access and the logos in the page are in PNG format

**Comment by jlpereira** [comment]
Nevermind, I edited the SVG file. The page is updated. Let me know if is okay  @debpaul
