### ISSUE TITLE
Overflow and text alignment

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonworks_homepage#3]
This problems are only present on Windows even with Chrome, Firefox, etc... probably related as how the scrollbars are handled there when the width is 100vw. 
On the screenshots is visible that with Edge and IE this problem is even more critical.

![edge 1](https://cloud.githubusercontent.com/assets/16530364/26438669/beb48f4c-40fa-11e7-92bb-2431037e9320.png)
![edge](https://cloud.githubusercontent.com/assets/16530364/26438670/bebbb8da-40fa-11e7-94fa-3af4d17823b9.png)
![internet-explorer](https://cloud.githubusercontent.com/assets/16530364/26438679/c938d78e-40fa-11e7-8b7b-b3f748b42ee4.png)

**Comment by BrianWalters** [comment]
Merged a change into develop that I think fixes this @jlpereira.

Also noticed the grid of sponsor images is busted in IE11. It's using [css grid](http://caniuse.com/#search=grid) — but it could be redone in flexbox.

**Comment by jlpereira** [comment]
Works perfect! Thanks @BrianWalters 

Now, you're right about the sponsor images, same problem on Edge too.
![edge](https://user-images.githubusercontent.com/16530364/27153995-d5ae2dae-5129-11e7-8867-9b5d6eb04f38.png)

**Comment by BrianWalters** [comment]
I looked at that more closely but stopped because I wasn't sure how to proceed. IE11 uses an old grid spec and that's causing problems. The grid layout looks really good on non-IE browsers which is why I didn't want to go for a flex layout immediately.

**Comment by BrianWalters** [comment]
Hey Matt/Jose, should I go ahead and turn this into a flex layout?

**Comment by mjy** [comment]
If you can you can do it under budget definitely.

M

**Comment by BrianWalters** [comment]
Pushed a fix.

**Comment by jlpereira** [comment]
Sorry the delay. Works perfect, thanks! @BrianWalters
