### ISSUE TITLE
Request- Show top nav bar on page opening

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_homepage#8]
From another reviewer. Perhaps show the nav bar with the three links immediately, then on scroll move logo/text up.   Plus one if you agree.

**Comment by mjy** [comment]
Requested tweak:

* When I land on the homepage, then I also see the top nav bar, but it doesn't have the logo or "TaxonWorks"
* When the user scrolls down, and is on the second panel then the Logo/TaxonWorks also appears on the nav bar.

**Comment by BrianWalters** [comment]
I merged into develop changes that I think address this. Let me know if this is what you pictured, Matt. Also check on a mobile device and tablet if you have them.

**Comment by mjy** [comment]
I"m not seeing the Logo/TaxonWorks appear on the left of the bar on the second page, but the rest looks good.

**Comment by BrianWalters** [comment]
I fixed the scrollbar for Firefox — now using a more supported API for scroll events and scroll position. Also adjusted the logo animation because Tyler hated the roll in (I love it).

**Comment by mjy** [comment]
Closing as outdated/complete.
